/*
 * Copyright 2025 VillageCompute Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package villagecompute.homepage.api.types;

import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;

import java.util.List;

/**
 * API type representing AI-generated category suggestions for Good Sites directory.
 *
 * <p>
 * Generated by LangChain4j integration for category assignment during bulk import workflow. Each suggestion includes
 * 1-3 recommended categories with reasoning and confidence score per Feature F13.14.
 *
 * <p>
 * <b>Policy References:</b>
 * <ul>
 * <li>P2/P10 (AI Budget Control): Categorization respects $500/month ceiling shared with feed tagging</li>
 * <li>F13.14 (Bulk Import): Admin review workflow with AI assistance and override capability</li>
 * </ul>
 *
 * @param suggestedCategories
 *            List of 1-3 recommended categories with reasoning (prefer most specific categories)
 * @param confidence
 *            Overall confidence score (0.0-1.0) for suggestion quality
 * @param overallReasoning
 *            High-level explanation for why these categories were selected
 */
public record AiCategorySuggestionType(@NotNull List<SuggestedCategory> suggestedCategories,
        @NotNull @DecimalMin("0.0") @DecimalMax("1.0") Double confidence, @NotNull String overallReasoning) {

    /**
     * Individual category suggestion with reasoning.
     *
     * @param categorySlug
     *            URL-friendly category identifier (e.g., "computers-programming-java")
     * @param categoryPath
     *            Human-readable category path (e.g., "Computers > Programming > Java")
     * @param reasoning
     *            Explanation for why this specific category was chosen
     */
    public record SuggestedCategory(@NotNull String categorySlug, @NotNull String categoryPath,
            @NotNull String reasoning) {
    }

    /**
     * Validates AI suggestion and ensures all fields meet constraints.
     *
     * @param suggestion
     *            the suggestion to validate
     * @return the validated suggestion
     * @throws IllegalArgumentException
     *             if validation fails
     */
    public static AiCategorySuggestionType validate(AiCategorySuggestionType suggestion) {
        if (suggestion.suggestedCategories() == null || suggestion.suggestedCategories().isEmpty()) {
            throw new IllegalArgumentException("No categories suggested");
        }

        if (suggestion.suggestedCategories().size() > 3) {
            throw new IllegalArgumentException(
                    "Too many categories suggested (max 3): " + suggestion.suggestedCategories().size());
        }

        if (suggestion.confidence() == null || suggestion.confidence() < 0.0 || suggestion.confidence() > 1.0) {
            throw new IllegalArgumentException("Invalid confidence score: " + suggestion.confidence());
        }

        if (suggestion.overallReasoning() == null || suggestion.overallReasoning().isBlank()) {
            throw new IllegalArgumentException("Overall reasoning is required");
        }

        // Validate each category
        for (SuggestedCategory cat : suggestion.suggestedCategories()) {
            if (cat.categorySlug() == null || cat.categorySlug().isBlank()) {
                throw new IllegalArgumentException("Category slug is required");
            }
            if (cat.categoryPath() == null || cat.categoryPath().isBlank()) {
                throw new IllegalArgumentException("Category path is required");
            }
            if (cat.reasoning() == null || cat.reasoning().isBlank()) {
                throw new IllegalArgumentException("Category reasoning is required");
            }
        }

        return suggestion;
    }
}
