package villagecompute.homepage.api.types;

import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;

import java.util.List;

/**
 * API type representing AI-generated tags for feed items.
 *
 * <p>
 * Generated by LangChain4j integration for content categorization, sentiment analysis, and topic extraction. Stored as
 * JSONB in {@code feed_items.ai_tags} column.
 *
 * <p>
 * <b>Policy References:</b>
 * <ul>
 * <li>P2/P10 (AI Budget Control): Tag generation respects $500/month ceiling via AiTaggingBudgetService</li>
 * </ul>
 *
 * @param topics
 *            extracted topics/keywords from article content
 * @param sentiment
 *            sentiment analysis: positive, negative, neutral, mixed
 * @param categories
 *            content categories (Technology, Business, Science, etc.)
 * @param confidence
 *            confidence score (0.0-1.0) for tag quality
 */
public record AiTagsType(@NotNull List<String> topics, @NotNull String sentiment, @NotNull List<String> categories,
        @NotNull @DecimalMin("0.0") @DecimalMax("1.0") Double confidence) {
}
