package villagecompute.homepage.api.types;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

/**
 * Type representing a pre-signed URL for temporary object access.
 *
 * <p>
 * Generated by StorageGateway to provide time-limited access to S3/R2 objects without exposing bucket credentials.
 *
 * <p>
 * <b>Policy P4:</b> Signed URLs implement privacy controls through short-lived access tokens.
 *
 * @param url
 *            pre-signed URL with embedded authentication signature
 * @param expiresAt
 *            ISO 8601 timestamp when URL expires
 * @param ttlMinutes
 *            time-to-live in minutes (24 hours for private, 7 days for public)
 * @param objectKey
 *            object key this URL grants access to
 */
public record SignedUrlType(@NotBlank String url, @NotBlank @JsonProperty("expires_at") String expiresAt,
        @NotNull @JsonProperty("ttl_minutes") Integer ttlMinutes,
        @NotBlank @JsonProperty("object_key") String objectKey) {
}
