-- // create_feed_items
-- Creates the feed_items table for aggregated news articles from RSS sources with AI tagging per Policy P2/P10.
-- Includes deduplication via item_guid (from RSS) and content_hash (for similarity detection).
-- AI tags stored as JSONB containing topics, sentiment, categories generated by LangChain4j.
-- Monthly partitioning planned for future (not implemented in this migration - see feed-governance.md).
-- TTL: 90 days for non-bookmarked items per Policy P14 (retention enforcement in future iteration).

CREATE TABLE feed_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id UUID NOT NULL REFERENCES rss_sources(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT,
    content TEXT,
    item_guid TEXT NOT NULL,
    content_hash TEXT,
    author TEXT,
    published_at TIMESTAMPTZ NOT NULL,
    ai_tags JSONB,
    ai_tagged BOOLEAN NOT NULL DEFAULT FALSE,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for common query patterns
CREATE UNIQUE INDEX idx_feed_items_guid ON feed_items(item_guid);
CREATE INDEX idx_feed_items_source_published ON feed_items(source_id, published_at DESC);
CREATE INDEX idx_feed_items_published ON feed_items(published_at DESC);
CREATE INDEX idx_feed_items_ai_tagged ON feed_items(ai_tagged) WHERE ai_tagged = FALSE;
CREATE INDEX idx_feed_items_content_hash ON feed_items(content_hash) WHERE content_hash IS NOT NULL;

-- GIN index for ai_tags JSONB queries (topic filtering, category search)
CREATE INDEX idx_feed_items_ai_tags ON feed_items USING GIN(ai_tags);

-- //@UNDO

DROP TABLE IF EXISTS feed_items;
